"use client";
import { useMemo,useState } from "react";
type RecordValue=string|number|boolean|null;
export function DataModule({title,resource,columns,labels,initial}:{title:string;resource:string;columns:readonly string[];labels:Record<string,string>;initial:Record<string,RecordValue>[]}){
 const [rows,setRows]=useState(initial),[q,setQ]=useState(""),[open,setOpen]=useState(false),[error,setError]=useState("");
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function create(form:FormData){const payload=Object.fromEntries(form);const res=await fetch("/api/resources/"+resource,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await res.json();if(!res.ok){setError(body.error||"Unable to save");return}setRows(x=>[body,...x]);setOpen(false)}
 return <section className="page"><div className="page-head"><div><span className="eyebrow">PRIDE LAW OPERATIONS</span><h1>{title}</h1><p>Authorized firm records protected by row-level security.</p></div><button className="primary" onClick={()=>setOpen(true)}>＋ Add record</button></div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter records…"/><span>{filtered.length} records</span></div><div className="card table-card"><table><thead><tr>{columns.map(c=><th key={c}>{labels[c]||c}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={String(r.id)}>{columns.map(c=><td key={c}>{format(r[c],c)}</td>)}</tr>)}</tbody></table></div>{open&&<div className="modal" role="dialog"><form action={create} className="modal-card"><h2>New {title.replace(/s$/,"")}</h2>{error&&<div className="error">{error}</div>}{columns.slice(0,6).map(c=><label key={c}>{labels[c]||c}<input name={c} required={["name","title","email"].includes(c)}/></label>)}<div><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save</button></div></form></div>}</section>
}
function format(v:RecordValue,key:string){if(v===null||v==="")return "—";if(["amount","balance","rate"].includes(key))return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v));if(typeof v==="boolean")return v?"Yes":"No";return String(v)}
